version: '3.7'

services:
  frontend:
    image: laercios/starwarsapp_frontend:latest
    working_dir: /app
    command: yarn serve
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/.editorconfig:/app/.editorconfig
      - ./app/package.json:/app/package.json
      - ./app/yarn.lock:/app/yarn.lock
    ports:
      - 8080:8080