version: '3.7'

services:
  frontend:
    image: laercios/starwarsapp_frontend:latest
    build:
      context: app
      dockerfile: ../Dockerfile
    working_dir: /app
    command: sleep infinity
    volumes:
      - ./app:/app/
    ports:
      - 8080:8080